Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 187, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 315, in render
    match = condition.eval(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 878, in eval
    return self.value.resolve(context, ignore_failures=True)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\functional.py", line 258, in inner
    self._setup()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\functional.py", line 398, in _setup
    self._wrapped = self._setupfunc()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 53, in __getitem__
    return self._session[key]
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sessions\backends\base.py", line 192, in _get_session
    self._session_cache = self.load()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 42, in load
    s = self._get_session_from_db()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sessions\backends\db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 492, in get
    num = len(clone)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 302, in __len__
    self._fetch_all()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 1507, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 57, in __iter__
    results = compiler.execute_sql(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1361, in execute_sql
    cursor.execute(sql, params)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

Watching for file changes with StatReloader
Profile request
Profile request
Importing BlpImagePlugin
Importing BmpImagePlugin
Importing BufrStubImagePlugin
Importing CurImagePlugin
Importing DcxImagePlugin
Importing DdsImagePlugin
Importing EpsImagePlugin
Importing FitsImagePlugin
Importing FitsStubImagePlugin
Importing FliImagePlugin
Importing FpxImagePlugin
Image: failed to import FpxImagePlugin: No module named 'olefile'
Importing FtexImagePlugin
Importing GbrImagePlugin
Importing GifImagePlugin
Importing GribStubImagePlugin
Importing Hdf5StubImagePlugin
Importing IcnsImagePlugin
Importing IcoImagePlugin
Importing ImImagePlugin
Importing ImtImagePlugin
Importing IptcImagePlugin
Importing JpegImagePlugin
Importing Jpeg2KImagePlugin
Importing McIdasImagePlugin
Importing MicImagePlugin
Image: failed to import MicImagePlugin: No module named 'olefile'
Importing MpegImagePlugin
Importing MpoImagePlugin
Importing MspImagePlugin
Importing PalmImagePlugin
Importing PcdImagePlugin
Importing PcxImagePlugin
Importing PdfImagePlugin
Importing PixarImagePlugin
Importing PngImagePlugin
Importing PpmImagePlugin
Importing PsdImagePlugin
Importing SgiImagePlugin
Importing SpiderImagePlugin
Importing SunImagePlugin
Importing TgaImagePlugin
Importing TiffImagePlugin
Importing WebPImagePlugin
Importing WmfImagePlugin
Importing XbmImagePlugin
Importing XpmImagePlugin
Importing XVThumbImagePlugin
Profile request
Profile request
Profile request
Profile request
Profile request
Profile request
Profile request
Profile request
check form validation
Internal Server Error: /post/1/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/tweet_detail.html
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'urls'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 14: 'urls', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post.audio_fie.url' not found. 'post.audio_fie.url' is not a valid view function or pattern name.
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing.): /post/new/
Forbidden (CSRF token missing.): /post/new/
Forbidden (CSRF token missing.): /post/new/
Forbidden (CSRF token missing.): /post/new/
Forbidden (CSRF token missing.): /post/new/
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing.): /post/new/
Forbidden (CSRF token missing.): /post/new/
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/4/delete/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/tweet_confirm_delete.html
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 70, in form_valid
    print(self.request.data)
AttributeError: 'WSGIRequest' object has no attribute 'data'
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 72, in form_valid
    print(form.audiofile)
AttributeError: 'TweetForm' object has no attribute 'audiofile'
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\mixins.py", line 73, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 184, in post
    return super().post(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 153, in post
    return self.form_valid(form)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 72, in form_valid
    print(form.audio_file)
AttributeError: 'TweetForm' object has no attribute 'audio_file'
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_78tJV2G.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_XVXu7HY.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_1uVIOnu.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_brs4CQe.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_78tJV2G.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_1uVIOnu.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_brs4CQe.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_XVXu7HY.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_brs4CQe.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_1uVIOnu.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_78tJV2G.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_XVXu7HY.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_78tJV2G.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_1uVIOnu.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_brs4CQe.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_XVXu7HY.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_1uVIOnu.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_brs4CQe.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_78tJV2G.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_XVXu7HY.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_78tJV2G.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_1uVIOnu.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_brs4CQe.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm_XVXu7HY.mp3
Not Found: /audio_files/Uyire-MassTamilan.fm.mp3
Not Found: /audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3' not found. '/media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 701, in __init__
    raise TemplateSyntaxError(
django.template.exceptions.TemplateSyntaxError: Could not parse the remainder: ' post.audio_file.url' from 'url post.audio_file.url'
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for '/media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3' not found. '/media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_B1Wsynw.mp3' is not a valid view function or pattern name.
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /favicon.ico
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /favicon.ico
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Internal Server Error: /post/7/delete/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: blog/tweet_confirm_delete.html
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /media/audio_files/Zariya_-_AR_Rahman_Ani_Choying_Farah_Siraj_-_Coke_Studio__MTV_Season_3_cokes_D2KCc9P.mp3
Not Found: /favicon.ico
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 505, in parse
    compile_func = self.tags[command]
KeyError: 'endblock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 42, in select_template
    return engine.get_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 507, in parse
    self.invalid_block_tag(token, command, parse_until)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 558, in invalid_block_tag
    raise self.error(
django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 63: 'endblock', expected 'empty' or 'endfor'. Did you forget to register or load this tag?
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed (POST): /
Method Not Allowed: /
Method Not Allowed (POST): /
Method Not Allowed: /
Not Found: /post/1/delete/
Method Not Allowed (POST): /
Method Not Allowed: /
Not Found: /post/4/delete/
Method Not Allowed (POST): /
Method Not Allowed: /
Not Found: /post/5/delete/
Not Found: /post/6/delete/
Not Found: /post/3/delete/
Not Found: /post/7/delete/
Not Found: /favicon.ico
Method Not Allowed (POST): /
Method Not Allowed: /
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed (POST): /
Method Not Allowed: /
Method Not Allowed (POST): /
Method Not Allowed: /
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed (POST): /
Method Not Allowed: /
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed (POST): /
Method Not Allowed: /
D:\Raihana\Voicetweet\Raihana_blog\blog\admin.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Method Not Allowed (POST): /
Method Not Allowed: /
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'create-post' not found. 'create-post' is not a valid view function or pattern name.
Not Found: /post/new/{audioUrl}
Not Found: /post/new/{audioUrl}
Not Found: /post/new/{audioUrl}
Not Found: /post/new/$audioUrl
Not Found: /post/new/$audioUrl
Not Found: /post/new/$audioUrl
Forbidden (CSRF token missing.): /post/new/
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Forbidden (CSRF token missing.): /post/new/
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Forbidden (CSRF token missing.): /post/new/
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 45, in create_post
    return render(request, 'blog/home.html', context)
NameError: name 'context' is not defined
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 47, in create_post
    return render(request,'post_create')
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: post_create
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 47, in create_post
    return render(request,'post_create')
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: post_create
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/new/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 47, in create_post
    return render(request,'post_create:tweet_form.html')
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: post_create:tweet_form.html
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /434c6ac7-584e-42fd-9a89-43b2e275f399
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /post/new/blog/home.html
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /blog/tweet_form.html
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /blog/tweet_form.html
Not Found: /post/new/blog/tweet_form.html
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /favicon.ico
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 30, in home
    'comments': Comment.objects.all().order_by('-date_posted')
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 1295, in order_by
    obj.query.add_ordering(*field_names)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\query.py", line 2167, in add_ordering
    self.names_to_path(item.split(LOOKUP_SEP), self.model._meta)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\query.py", line 1677, in names_to_path
    raise FieldError(
django.core.exceptions.FieldError: Cannot resolve keyword 'date_posted' into field. Choices are: c_audio_file, c_author, c_author_id, c_date_posted, id, tweet, tweet_id
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 176, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\engine.py", line 158, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loaders\base.py", line 28, in get_template
    return Template(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 154, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 200, in compile_nodelist
    return parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 293, in do_extends
    nodelist = parser.parse()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 232, in do_block
    nodelist = parser.parse(("endblock",))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 854, in do_for
    nodelist_loop = parser.parse(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 513, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 511, in parse
    compiled_result = compile_func(self, token)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 954, in do_if
    nodelist = parser.parse(("elif", "else", "endif"))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 484, in parse
    raise self.error(token, e)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 482, in parse
    filter_expression = self.compile_filter(token.contents)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 600, in compile_filter
    return FilterExpression(token, self)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 696, in __init__
    filter_func = parser.find_filter(filter_name)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 606, in find_filter
    raise TemplateSyntaxError("Invalid filter: '%s'" % filter_name)
django.template.exceptions.TemplateSyntaxError: Invalid filter: 'crispy'
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /post/table/
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/comment/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'FieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 81, in create_comment
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 65, in url
    self._require_file()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError(
ValueError: The 'c_audio_file' attribute has no file associated with it.
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/comment/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 79, in create_comment
    comment.save()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\base.py", line 806, in save
    self.save_base(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\base.py", line 857, in save_base
    updated = self._save_table(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\base.py", line 1000, in _save_table
    results = self._do_insert(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\base.py", line 1041, in _do_insert
    return manager._insert(
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 1434, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1620, in execute_sql
    for sql, params in self.as_sql():
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1547, in as_sql
    value_rows = [
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1548, in <listcomp>
    [
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1549, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\sql\compiler.py", line 1497, in pre_save_val
    return field.pre_save(obj, add=True)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 314, in pre_save
    if file and not file._committed:
AttributeError: 'MultiValueDict' object has no attribute '_committed'
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /post/comment/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'FieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 81, in create_comment
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 65, in url
    self._require_file()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError(
ValueError: The 'c_audio_file' attribute has no file associated with it.
Internal Server Error: /post/comment/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'FieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 81, in create_comment
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 65, in url
    self._require_file()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError(
ValueError: The 'c_audio_file' attribute has no file associated with it.
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 875, in _resolve_lookup
    current = current[bit]
TypeError: 'FieldFile' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1059, in render
    output = self.filter_expression.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 712, in resolve
    obj = self.var.resolve(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 842, in resolve
    value = self._resolve_lookup(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 885, in _resolve_lookup
    current = getattr(current, bit)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 65, in url
    self._require_file()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\fields\files.py", line 40, in _require_file
    raise ValueError(
ValueError: The 'c_audio_file' attribute has no file associated with it.
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\models.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\forms.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
check form validation
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 63, in render
    result = block.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 238, in render
    nodelist.append(node.render_annotated(context))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'post-detail' not found. 'post-detail' is not a valid view function or pattern name.
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
Not Found: /favicon.ico
D:\Raihana\Voicetweet\Raihana_blog\blog\views.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /logout/asset/btn_google_signin_dark_focus_web.png
Not Found: /logout/asset/btn_google_signin_dark_focus_web.png
Not Found: /logout/asset/btn_google_signin_dark_focus_web.png
Not Found: /logout/asset/btn_google_signin_dark_focus_web.png
Not Found: /logout/asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /account/login
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Internal Server Error: /accounts/google/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\oauth2\views.py", line 80, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\base\mixins.py", line 18, in dispatch
    return self.login(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\oauth2\views.py", line 108, in login
    app = provider.get_app(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\base\provider.py", line 30, in get_app
    return adapter.get_app(request, self.id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\adapter.py", line 204, in get_app
    app = SocialApp.objects.get_current(provider, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\models.py", line 31, in get_current
    app = self.get(sites__id=site.id, provider=provider)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.
Internal Server Error: /accounts/google/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\oauth2\views.py", line 80, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\base\mixins.py", line 18, in dispatch
    return self.login(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\oauth2\views.py", line 108, in login
    app = provider.get_app(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\base\provider.py", line 30, in get_app
    return adapter.get_app(request, self.id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\adapter.py", line 204, in get_app
    app = SocialApp.objects.get_current(provider, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\models.py", line 31, in get_current
    app = self.get(sites__id=site.id, provider=provider)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.
D:\Raihana\Voicetweet\Raihana_blog\django_project\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\urls.py changed, reloading.
Watching for file changes with StatReloader
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /accounts/google/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\oauth2\views.py", line 80, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\base\mixins.py", line 18, in dispatch
    return self.login(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\oauth2\views.py", line 108, in login
    app = provider.get_app(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\providers\base\provider.py", line 30, in get_app
    return adapter.get_app(request, self.id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\adapter.py", line 204, in get_app
    app = SocialApp.objects.get_current(provider, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\allauth\socialaccount\models.py", line 31, in get_current
    app = self.get(sites__id=site.id, provider=provider)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.
Internal Server Error: /admin/logout/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 403, in logout
    return LogoutView.as_view(**defaults)(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 132, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 185, in get
    context = self.get_context_data(**kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 166, in get_context_data
    current_site = get_current_site(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 103, in get_context_data
    current_site = get_current_site(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 103, in get_context_data
    current_site = get_current_site(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 103, in get_context_data
    current_site = get_current_site(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
Not Found: /asset/btn_google_signin_dark_focus_web.png
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 103, in get_context_data
    current_site = get_current_site(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
Not Found: /asset/btn_google_signin_dark_focus_web.png
Internal Server Error: /admin/login/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\admin\sites.py", line 440, in login
    return LoginView.as_view(**defaults)(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\utils\decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\decorators\cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 67, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\base.py", line 119, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\views\generic\edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\auth\views.py", line 103, in get_context_data
    current_site = get_current_site(self.request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\shortcuts.py", line 14, in get_current_site
    return Site.objects.get_current(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\contrib\sites\models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\db\models\query.py", line 496, in get
    raise self.model.DoesNotExist(
django.contrib.sites.models.Site.DoesNotExist: Site matching query does not exist.
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /asset/btn_google_signin_dark_focus_web.png
Not Found: /asset/btn_google_signin_dark_focus_web.png
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login' not found. 'accounts/login' is not a valid view function or pattern name.
D:\Raihana\Voicetweet\Raihana_blog\django_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login' not found. 'accounts/login' is not a valid view function or pattern name.
Internal Server Error: /logout/
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\response.py", line 92, in rendered_content
    return template.render(context, self._request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login' not found. 'accounts/login' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login' not found. 'accounts/login' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'google-login' not found. 'google-login' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'google-login' not found. 'google-login' is not a valid view function or pattern name.
Internal Server Error: /
Traceback (most recent call last):
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Raihana\Voicetweet\Raihana_blog\blog\views.py", line 34, in home
    return render(request, 'blog/home.html', context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\shortcuts.py", line 24, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader.py", line 62, in render_to_string
    return template.render(context, request)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\backends\django.py", line 62, in render
    return self.template.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 175, in render
    return self._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\loader_tags.py", line 157, in render
    return compiled_parent._render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 167, in _render
    return self.nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 322, in render
    return nodelist.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 1000, in <listcomp>
    return SafeString("".join([node.render_annotated(context) for node in self]))
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\base.py", line 958, in render_annotated
    return self.render(context)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\template\defaulttags.py", line 472, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\base.py", line 88, in reverse
    return resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "D:\Raihana\DjangoCRUD\DjangoCRUD\venv\lib\site-packages\django\urls\resolvers.py", line 802, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'accounts/login/' not found. 'accounts/login/' is not a valid view function or pattern name.
D:\Raihana\Voicetweet\Raihana_blog\django_project\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /favicon.ico
Not Found: /logout/accounts/login/
Not Found: /logout/accounts/login/
Watching for file changes with StatReloader
Starting new HTTPS connection (1): accounts.google.com:443
https://accounts.google.com:443 "POST /o/oauth2/token HTTP/1.1" 200 None
Starting new HTTPS connection (1): www.googleapis.com:443
https://www.googleapis.com:443 "GET /oauth2/v1/userinfo?access_token=ya29.a0ARrdaM9ORk0IB_WeHnbBCx1YuktyX4p31z6XD9zJFXi0oiBVbSobLJXJJOtb0QfTcp1RRQbG-roL_fzxc4jorCNUkPrMO2g0-AIwxmF2g7QAu6j54xkgT-nTjhkbgb3Zib01IWctZhCeVdi7AoDetRq265ID&alt=json HTTP/1.1" 200 None
D:\Raihana\Voicetweet\Raihana_blog\django_project\settings.py changed, reloading.
Watching for file changes with StatReloader
